/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_y4sec_encryptor_core_CodeEncryptor */

#ifndef _Included_org_y4sec_encryptor_core_CodeEncryptor
#define _Included_org_y4sec_encryptor_core_CodeEncryptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_y4sec_encryptor_core_CodeEncryptor
 * Method:    encrypt
 * Signature: ([BI[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_y4sec_encryptor_core_CodeEncryptor_encrypt
        (JNIEnv *, jclass, jbyteArray, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
